import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';

// Absolute root folder directory path,
// because this file is being executed at the root somehow !!!
const absDirPath = path.join(process.cwd(), 'posts');

export function getSortedPostsData() {
    // Array of file names within the /posts folder at the root
    const fileNames = fs.readdirSync(absDirPath);

    const unsortedPostsData = fileNames.map((filename) => {
        // id's generated by removing .md at the end of strings
        const id = filename.replace(/\.md$/, '');
        // we want to store file content in a variable
        const fileContent = fs.readFileSync(
            path.join(absDirPath, filename),
            'utf8'
        );
        // let's extract only the meta data
        const fileMatter = matter(fileContent);

        return {
            id,
            ...fileMatter.data
        };
    });

    return unsortedPostsData.sort(sortDates);
}

// basic sort function for dates
function sortDates(a, b) {
    if (new Date(a.date).getTime() > new Date(b.date).getTime()) {
        return 1;
    } else if (new Date(a.date).getTime() < new Date(b.date).getTime()) {
        return -1;
    } else {
        return 0;
    }
}
